spring:
    thymeleaf:
        cache: false
        enabled: true
        encoding: UTF-8
        mode: HTML
        prefix: classpath:/templates/
        servlet:
            content-type: text/html
        suffix: .html
    resources:
        static-locations: classpath:/static/

#日志
logging:
  config: classpath:log4j2.xml